/*
  Warnings:

  - The values [PROJECT_STATUS_CHANGED,PAYMENT_STATUS_CHANGED,TASK_STATUS_CHANGED,TASK_PRIORITY_CHANGED] on the enum `ActivityType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ActivityType_new" AS ENUM ('PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_COMPLETE', 'PROJECT_REMOVED', 'PROJECT_CANCEL', 'PROJECT_PAUSE', 'PROJECT_IN_PROGRESS', 'PAYMENT_STATUS_NOT_PAID', 'PAYMENT_STATUS_PAID', 'PAYMENT_STATUS_IN_INSTALLMENTS', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'TASK_CREATED', 'TASK_UPDATED', 'TASK_COMPLETED', 'TASK_REMOVED', 'TASK_STATUS_PENDING', 'TASK_STATUS_IN_PROGRESS', 'TASK_STATUS_REVIEW', 'TASK_STATUS_COMPLETED', 'TASK_STATUS_CANCEL', 'TASK_PRIORITY_LOW', 'TASK_PRIORITY_MEDIUM', 'TASK_PRIORITY_HIGH', 'TASK_PRIORITY_URGENT', 'COMMENT_ADDED', 'COMMENT_UPDATED', 'COMMENT_REMOVED', 'PAYMENT_ADDED', 'PAYMENT_UPDATED', 'PAYMENT_REMOVED');
ALTER TABLE "ActivityLog" ALTER COLUMN "type" TYPE "ActivityType_new" USING ("type"::text::"ActivityType_new");
ALTER TYPE "ActivityType" RENAME TO "ActivityType_old";
ALTER TYPE "ActivityType_new" RENAME TO "ActivityType";
DROP TYPE "public"."ActivityType_old";
COMMIT;
